:Author: rahularepaka
:Email: rahul.arepaka@gmail.com

== Project : ALCOHOL DETECTION WITH ENGINE LOCK MECHANISM

We usually come across drink and driving cases where drunk drivers
crash their cars under the influence of alcohol causing damage to
property and life. So here we propose an innovative system to
eliminate such cases. Our proposed system would be constantly
monitoring the driver breath by placing it on the driver wheel or
somewhere the driver’s breath can be constantly monitored by it. So,
if a driver is drunk and tries to drive, the system detects alcohol
presence in his/her breath and locks the engine so that the vehicle
fails to start. The system uses an Arduino, PC fan, alcohol sensor,
and buzzer. The Arduino(microcontroller) on encountering high
alcohol signal from the alcohol sensor indicates alcohol detection
through buzzer and stops the Fan to demonstrate as engine locking.
When alcohol is detected after engine starting, the system locks the
engine at that time. This Project presents an innovative way of
protecting automobiles from drunken drivers for safeguarding them
by Arduino and its sensors. Programming language used in the Arduino is C++.

== Objective of the Project
Every system is automated in order to face new challenges. In
the present days Automated systems have fewer manual operations,
flexibility, reliability and accurate. Due to this demand every field prefers
automated control systems. We usually come across drink and driving
cases where drunk drivers crash their cars under the influence of alcohol
causing damage to property and life. So here we propose an innovative
system to eliminate such cases. Our proposed system would be constantly
monitoring the driver breath by placing it on the driver wheel or somewhere
the driver’s breath can be constantly monitored by it. So, if a driver is drunk
and tries to drive the system detects alcohol presence in his/her breathe
and locks the engine so that the vehicle fails to start. In another case if the
driver is not drunk while he starts the vehicle and engine is started but
he/she drinks while driving the sensor still detects alcohol in his breath and
stops the engine so that the car would not accelerate any further and driver
can steer it to roadside. So, the alcohol sensor is used to monitor uses
breath and constantly sends signals to the microcontroller.

== Parts Used : 
1.Arduino UNO
2.Breadboard
3.12V PC Fan to represent a Engine
4.Power Supply or Batteries
5.Alcohol Sensor MQ3
6.Arduino UNO USB cable
7.Jumper Cables M/M and M/F
8.LED's
9.Relay
10.Buzzer

== Step 1: Installation

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram attached to the sketch.
Note : This is only connection for the Sensor and Relay to the Arduino UNO.

![circuit diagram](D:\Pictures)


== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Alcohol_Sensor_MQ3                => Arduino sketch folder
  ├── Alcohol_Sensor_MQ3.ino       => main Arduino file
  └── ReadMe.adoc                  => this file
....

=== Contributing
To contribute to this project please contact Rahul Arepaka <rahul.arepaka@gmail.com>
